### ISSUE TITLE
Failed to load.

### ISSUE THREAD

**Issue by Mpsys** [pinkipi/skill-prediction#10]
[proxy] preloading modules

[proxy] failed to load "skill-prediction-master"
Error: ENOENT: no such file or directory, open 'C:\Games\tera-proxy_3\tera-proxy\node_modules\tera-data\src\js\map\sysmsg.map'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at Object.load (C:\Games\tera-proxy_3\tera-proxy\node_modules\tera-data-parser\lib\sysmsg\index.js:21:19)
    at Object.<anonymous> (C:\Games\tera-proxy_3\tera-proxy\node_modules\tera-data-parser\lib\sysmsg\index.js:50:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)

[sls] server list overridden
[game] listening on 127.0.0.1:9246
[game] listening on 127.0.0.1:9247
[game] listening on 127.0.0.1:9248
[game] listening on 127.0.0.1:9249
[game] listening on 127.0.0.1:9250
>

**Comment by natedog1177** [comment]
Update tera-proxy or the tera-data/tera-data-parser modules inside of it.
