### ISSUE TITLE
Only get disconnected when playing as lancer

### ISSUE THREAD

**Issue by mateustaio** [pinkipi/skill-prediction#29]
Hi, when i'm playing with lancer i'm always disconnected after some time, this is the error that tera-proxy shows:

[09:13:14 GMT-0300]  INFO tera-proxy-game: [dispatch] loaded "auto-negotiate"
[09:13:14 GMT-0300]  INFO tera-proxy-game: [dispatch] loaded "autovanguard"
[09:13:14 GMT-0300]  INFO tera-proxy-game: [dispatch] loaded "skill-prediction"
[09:13:14 GMT-0300]  INFO tera-proxy: routing connection (from = 127.0.0.1:49950
, to = 208.67.49.68:10001)
[09:13:14 GMT-0300]  INFO tera-proxy-game: [dispatch] switching to protocol vers
ion 313623
[09:19:49 GMT-0300] ERROR tera-proxy-game: [dispatch] handle: error running hook
 for C_START_SKILL<1>
hook: bound startSkill in skill-prediction
data: { skill: 67189564,
  w: -5108,
  x1: 49169.59765625,
  y1: -72168.6171875,
  z1: -5717.64404296875,
  x2: 0,
  y2: 0,
  z2: 0,
  unk1: 1,
  unk2: 0,
  unk3: 0,
  target: Long { low: 209814, high: 819200, unsigned: true } }
error: Cannot read property 'name' of undefined
    at sendSystemMessage (C:\Users\Mateus\Desktop\tera-proxy\bin\node_modules\sk
ill-prediction\index.js:780:69)
    at sendStartSkill (C:\Users\Mateus\Desktop\tera-proxy\bin\node_modules\skill
-prediction\index.js:295:5)
    at startSkill (C:\Users\Mateus\Desktop\tera-proxy\bin\node_modules\skill-pre
diction\index.js:195:10)
[09:19:49 GMT-0300] ERROR tera-proxy-game: [dispatch] handle: error running hook
 for C_START_SKILL<1>
hook: bound startSkill in skill-prediction
data: { skill: 67189564,
  w: -5108,
  x1: 49169.59765625,
  y1: -72168.6171875,
  z1: -5717.64404296875,
  x2: 0,
  y2: 0,
  z2: 0,
  unk1: 1,
  unk2: 0,
  unk3: 0,
  target: Long { low: 209814, high: 819200, unsigned: true } }
error: Cannot read property 'name' of undefined
    at sendSystemMessage (C:\Users\Mateus\Desktop\tera-proxy\bin\node_modules\sk
ill-prediction\index.js:780:69)
    at sendStartSkill (C:\Users\Mateus\Desktop\tera-proxy\bin\node_modules\skill
-prediction\index.js:295:5)
    at startSkill (C:\Users\Mateus\Desktop\tera-proxy\bin\node_modules\skill-pre
diction\index.js:195:10)
C:\Users\Mateus\Desktop\tera-proxy\bin\node_modules\skill-prediction\index.js:78
0
                let message = '@' + sysmsg.maps.get(dispatch.base.protocolVersio
n).name.get(type)

  ^

TypeError: Cannot read property 'name' of undefined
    at sendSystemMessage (C:\Users\Mateus\Desktop\tera-proxy\bin\node_modules\sk
ill-prediction\index.js:780:69)
    at Timeout.sendStartSkill [as _onTimeout] (C:\Users\Mateus\Desktop\tera-prox
y\bin\node_modules\skill-prediction\index.js:295:5)
    at ontimeout (timers.js:399:18)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
Press any key to continue. . .

Sometimes i can play for more time before getting disconnected and sometimes after 5 min the error happens, i have other classes and none of them get this error when playing for any amount of time, just when i'm playing my lancer this happens, can any of you help me pls? Thank you.

**Comment by pinkipi** [comment]
See #34
