### ISSUE TITLE
no skills working in KR server

### ISSUE THREAD

**Issue by Leibeun** [pinkipi/skill-prediction#36]
no skill is working on kr server, whatever character i try, whatever skill i use, no skill works in game. 
Whenever i try to use, a message appears in cmd

[01:03:15 GMT+0900] ERROR tera-proxy-game: [dispatch] handle: error running hook for C_START_SKILL<1>
hook: bound startSkill in skill-prediction-master
data: { skill: 67118964,
  w: -3906,
  x1: 16277.4306640625,
  y1: 1268.5728759765625,
  z1: -4411.82177734375,
  x2: 0,
  y2: 0,
  z2: 0,
  unk1: 1,
  unk2: 0,
  unk3: 0,
  target: Long { low: 0, high: 0, unsigned: true } }
error: Cannot read property 'name' of undefined
    at sendSystemMessage (C:\Users\레이븐\Desktop\tera-proxy\bin\node_modules\skill-prediction-master\index.js:877:69)
    at sendStartSkill (C:\Users\레이븐\Desktop\tera-proxy\bin\node_modules\skill-prediction-master\index.js:287:4)
    at startSkill (C:\Users\레이븐\Desktop\tera-proxy\bin\node_modules\skill-prediction-master\index.js:231:10)

Screenshot of in game error
[http://s1244.photobucket.com/user/Leibeun/media/_zpsdier0arw.jpg.html](url)

Screenshot of the whole commandline
[http://s1244.photobucket.com/user/Leibeun/media/ddd_zpsbckwh9cf.jpg.html?sort=3&o=0](url)

**Comment by a25816978** [comment]
Hello, my friend send me tera proxy and   it works on kr-tera, but it still have some skill problem with certain classes would you please help me make patch on k-tera proxy  just like on the other version ?
